# Nom del lloc
site_name: Desarrollo Web en Entorno Servidor (DWES)

# Carpeta amb el documents font
docs_dir: 'md'

# Carpeta on es generarà el lloc web (mkdocs build)
site_dir: 'docs'

# Adreça on s'executa el server local (mkdocs serve)
dev_addr: localhost:4001

# Navegació dels documents
# nav:
#   - Títol: Document.md
nav:
  - Inicio: index.md
  - UD 1 Arquitectura Web:
     - 1.1 Introducción: ud01/ud0101.md
     - 1.2 Cliente/servidor: ud01/ud0102.md
     - 1.3 Arquitectura de 3 capas: ud01/ud0103.md
     - 1.4 MVC: ud01/ud0104.md
     - 1.5 Decisiones de diseño: ud01/ud0105.md
     - 1.6 Herramientas: ud01/ud0106.md
     - 1.7 Puesta en marcha: ud01/ud0107.md
     - 1.8 Manual Docker: ud01/ud0108.md
     - Descargas: ud01/ud01de.md
     - Actividades: ud01/ud01ac.md
     - Referencias: ud01/ud0109.md
  - UD 2 Lenguaje PHP:
     - 2.1 Introducción: ud02/ud0201.md
     - 2.2 PHP: ud02/ud0202.md
     - 2.3 Operadores: ud02/ud0203.md
     - 2.4 Arrays: ud02/ud0204.md
     - 2.5 Funciones: ud02/ud0205.md
     - 2.6 Funciones predefinidas: ud02/ud0206.md
     - 2.7 Expresiones regulares: ud02/ud0207.md
     - Actividades: ud02/ud02ac.md
     - Referencias: ud02/ud0208.md
  - UD 3 PHP Orientado a Objetos: default.md
  - UD 4 Programación Web: default.md
  - UD 5 Herramientas Web: default.md
  - UD 6 Acceso a Base de Datos: default.md
  - UD 7 Framework Laravel: default.md
  - UD 8 Laravel avanzado: default.md

# Extensions
markdown_extensions:
  - admonition
  - attr_list         # permet afegir atributs a les etiquetes html
  # pymdownx és una col·leccio per escritura tècnica. S'instal·la per defecte
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true

# Tema a triar
theme:
  name: material  # selecció del tema
  logo: logo3.png
  palette:
   # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Canvia a mode oscur
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Canvia a mode normal
  features:
    # utilitats de copia de codi
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer       # footer de la pagina, amb navegació
    - navigation.top    # boto flotant de tornar a dalt

# Altres afegits
plugins:
  - search      # plugin del quadre cerca
  #- mkdocs-awesome-pages-plugin  # per a caixe awesomebox
  #- pdf-export  # plugin per exportar a pdf
  #- mkdocs-pdf-export-plugin

extra:
  favicon: favicon.ico
