# Nom del lloc
site_name: Desarrollo Web en Entorno Servidor (DWES)

# Carpeta amb el documents font
docs_dir: 'md'

# Carpeta on es generarà el lloc web (mkdocs build)
site_dir: 'docs'

# Adreça on s'executa el server local (mkdocs serve)
dev_addr: localhost:4001

# Navegació dels documents
# nav:
#   - Títol: Document.md
nav:
  - Inicio: index.md
  - Bloc I - PHP:
    - UD 1 Arquitectura Web:
        - 1.1 Introducción: ud01/ud0101.md
        - 1.2 Cliente/servidor: ud01/ud0102.md
        - 1.3 Arquitectura de 3 capas: ud01/ud0103.md
        - 1.4 MVC: ud01/ud0104.md
        - 1.5 Decisiones de diseño: ud01/ud0105.md
        - 1.6 Herramientas: ud01/ud0106.md
        - 1.7 Puesta en marcha: ud01/ud0107.md
        - 1.8 Manual Docker: ud01/ud0108.md
        - Descargas: ud01/ud01de.md
        - Actividades: ud01/ud01ac.md
        - Referencias: ud01/ud01re.md
    - UD 2 Lenguaje PHP:
        - 2.1 Introducción: ud02/ud0201.md
        - 2.2 PHP: ud02/ud0202.md
        - 2.3 Operadores: ud02/ud0203.md
        - 2.4 Arrays: ud02/ud0204.md
        - 2.5 Funciones: ud02/ud0205.md
        - 2.6 Funciones predefinidas: ud02/ud0206.md
        - 2.7 Expresiones regulares: ud02/ud0207.md
        - Actividades: ud02/ud02ac.md
        - Referencias: ud02/ud02re.md
    - UD 3 PHP OO:
        - 3.1 Introducción: ud03/ud0301.md
        - 3.2 Clases y objetos: ud03/ud0302.md
        - 3.3 Encapsulación: ud03/ud0303.md
        - 3.4 Constructor: ud03/ud0304.md
        - 3.5 Clases estáticas: ud03/ud0305.md
        - 3.6 Introspección: ud03/ud0306.md
        - 3.7 Herencia: ud03/ud0307.md
        - 3.8 Clases abstractas: ud03/ud0308.md
        - 3.9 Clases final: ud03/ud0309.md
        - 3.10 Interfaces: ud03/ud0310.md
        - 3.11 Métodos encadenados: ud03/ud0311.md
        - 3.12 Métodos mágicos: ud03/ud0312.md
        - 3.13 Espacio de nombres: ud03/ud0313.md
        - 3.14 Gestión de errores: ud03/ud0314.md
        - 3.15 Excepciones: ud03/ud0315.md
        - 3.16 SPL: ud03/ud0316.md
        - Actividades: ud03/ud03ac.md
        - Referencias: ud03/ud03re.md
    - UD 4 Programación Web:
        - 4.1 Introducción: ud04/ud0401.md
        - 4.2 Variable de servidor: ud04/ud0402.md
        - 4.3 Formularios: ud04/ud0403.md
        - 4.4 Cabeceras de respuesta: ud04/ud0404.md
        - 4.5 Gestión de estado: ud04/ud0405.md
        - 4.6 Autenticación de usuarios: ud04/ud0406.md
        - Actividades: ud04/ud04ac.md
        - Referencias: ud04/ud04re.md
    - UD 5 Acceso a Base de Datos:
        - 5.1 Introducción: ud06/ud0601.md
        - 5.2 Instalación: ud06/ud0602.md
        - 5.3 Estructura de BD: ud06/ud0603.md
        - 5.4 Chollometro: ud06/ud0604.md
        - 5.5 SQL: ud06/ud0605.md
        - 5.6 phpMyAdmin: ud06/ud0606.md
        - 5.7 MySQLi: ud06/ud0607.md
        - 5.8 PHP Data Objects-PDO: ud06/ud0608.md
        - 5.9 login & password: ud06/ud0609.md
        - 5.10 Acceso a ficheros: ud06/ud0610.md
        - Actividades: ud06/ud06ac.md
        - Referencias: ud06/ud6re.md
  - Bloc II - Laravel:
    - UD 6 Herramientas Web:
        - 6.1 Introducción: ud05/ud0501.md
        - 6.2 Composer: ud05/ud0502.md
        - 6.3 Monolog: ud05/ud0503.md
        - 6.4 Documentación con phpDocumentor: ud05/ud0504.md
        - 6.5 Web Scraping: ud05/ud0505.md
        - 6.6 Pruebas con phpUnit: ud05/ud0506.md
        - Actividades: ud05/ud05ac.md
        - Referencias: ud05/ud05re.md
    - UD 7 Framework:
        - 7.1 Introducció: ud07/ud0701.md
        - 7.2 Frameworks: ud07/ud0702.md
        - 7.3 Programari necessari: ud07/ud0703.md
        - 7.4 Primeres passes: ud07/ud0704.md
        - 7.5 Rutes: ud07/ud0705.md
        - 7.6 Vistes amb Blade: ud07/ud0706.md
        - 7.7 Estils i Javascript: ud07/ud0707.md
        - Activitats: ud07/ud07ac.md
        - Referències: ud07/ud07re.md
    - UD 8 Controladors:
        - 8.1 Controladors i tipus: ud08/ud0801.md
        - 8.2 Injecció i dependències: ud08/ud0802.md
    - UD 9 Model de dades:
        - 9.1 Accés a base de dades: ud09/ud0901.md
        - 9.2 Migracions: ud09/ud0902.md
        - 9.3 Model de dades: ud09/ud0903.md
        - 9.4 Relacions entre models: ud09/ud0904.md
        - 9.5 Seeders i factories: ud09/ud0905.md
        - 9.6 Query Builder i ús de dades: ud09/ud0906.md
    - UD 10 Formularis i validacions:
        - 10.1 Definició de formularis: ud10/ud1001.md
        - 10.2 Validació de dades: ud10/ud1002.md
    - UD 11 Serveis REST:
        - 11.1 Concepte de servei REST: ud11/ud1101.md
        - 11.2 Creació de serveis REST: ud11/ud1102.md
        - 11.3 Prova de serveis REST: ud11/ud1103.md

# Extensions
markdown_extensions:
  - admonition
  - attr_list         # permet afegir atributs a les etiquetes html
  # pymdownx és una col·leccio per escritura tècnica. S'instal·la per defecte
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true

# Tema a triar
theme:
  name: material  # selecció del tema
  logo: logo.png
  palette:
   # Boto que canvia a mode oscur
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Canvia a mode oscur
    # Botó que canvia a mode clar
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Canvia a mode normal
  features:
    # utilitats de copia de codi
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.footer       # footer de la pagina, amb navegació
    - navigation.top    # boto flotant de tornar a dalt

# Altres afegits
plugins:
  - search      # plugin del quadre cerca
  #- mkdocs-awesome-pages-plugin  # per a caixe awesomebox
  #- pdf-export  # plugin per exportar a pdf
  #- mkdocs-pdf-export-plugin

extra:
  favicon: favicon.ico
